# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    sudo apt-get install build-essential
    rm -rf ~/..node-gyp
    rm -rf ~/.npmrc
    npm install -g @angular/cli@1.7.4
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'dist/'
  displayName: "Npm install in the dist folder for express"

- script: |  
    npm install -g firebase-tools
    firebase --version
    firebase deploy --token 1//03Ncp0lDmQsG9CgYIARAAGAMSNwF-L9Iruch_pED-PZmSpXqmhAveOg34_ubImcImjSAv_GYqVbh2aauRFidcv7ehQX9wIsVjmyw --only hosting:gutblatt --message "Build: $(Build.BuildNumber) \n Sha: $(Build.SourceVersion)"
  env: 
    Sha: $(Build.SourceVersion)
    BuildId: $(Build.BuildId)
  displayName: "Deploy to Gutblatt (Firebase)"
  
